### ISSUE TITLE
Partially limit actions on graph entities

### ISSUE THREAD

**Issue by riccardolocci** [uber/react-digraph#195] opened 2020-01-29 18:05 UTC
I have a graph generate from a JSON, and I would like to allow the nodes to be moved, but block node creation/deletion and edge swap/creation/deletion.

The `readOnly` prop is almost what I need, but obviously I cannot change nodes' positions.

Is there a way to block all the actions except for nodes' updates (if not in `readOnly` mode) or to allow only nodes' updates (`readOnly` mode)

Thank you

**Comment by ajbogh** [comment] 2020-01-29 19:30
You can pass any function to the onUpdateNode callback or any other callbacks. You can even pass empty functions to prevent certain callbacks from affecting the data.

```
onUpdateNode={() => {
  // do nothing or do very specific things like ignoring x/y updates.
}}
onDeleteNode={() => {}}
```

**Comment by riccardolocci** [comment] 2020-02-03 18:28
I finally solved by using a combination of `readOnly` mode and `onSelectNode` + `onBackgroundClick`.
Dealing with "`editMode`" and passing empty functions only resulted in more troubles, particularly with edges, since there is no way to completely handle the "lifecycle" of edges (e.g.: I had a problem of dangling edges while trying to block edge swaps).

It could be useful to add a way to freely move nodes in `readOnly` mode, maybe a drag-and-drop handler.

**Comment by ajbogh** [comment] 2020-02-04 07:22
Thanks @riccardolocci. We would appreciate any PR that could help solve your issue. At this point since you have used other methods of solving this, I will close the issue.

You are welcome to reopen it if you can provide an example that could reproduce your issue so that we can help further.

**Closed by ajbogh** 2020-02-04 07:22 UTC
