### ISSUE TITLE
There's a error or a forgotten recommendation?

### ISSUE THREAD

**Issue by MichelDiz** [uber/react-digraph#57] opened 2018-08-21 03:08 UTC
```
./~/react-digraph/dist/components/graph-view.js
Module not found: Error: Cannot resolve module 'd3' in /Users/micheldiz/test/node_modules/react-digraph/dist/components
 @ ./~/react-digraph/dist/components/graph-view.js 42:9-22

These dependencies were not found:

* d3 in ./~/react-digraph/dist/components/graph-view.js
* radium in ./~/react-digraph/dist/components/graph-view.js, ./~/react-digraph/dist/components/graph-controls.js
* react-icons/lib/fa/expand in ./~/react-digraph/dist/components/graph-controls.js
* react-icons/lib/fa/info-circle in ./~/react-digraph/dist/components/graph-controls.js
```

**Comment by ajbogh** [comment] 2018-10-09 16:35
This may have been fixed in 4.1.5 or 4.1.6. We used to require d3 as a peerDependency, but now we're bundling it in the dependencies. If you are still using the older version you can install d3 yourself using either npm or a script tag and it should work. Try upgrading to the latest 4.x release to see if the issue is resolved.

**Closed** 2018-11-13 00:47 UTC
